import Foundation
import Testing

@testable import HydraCore

/// Gemma's tower geometry, and the places it differs from Qwen's.
///
/// The two towers share a depth and a width and almost nothing else. Most of these tests state a
/// difference in a form that fails if someone later "unifies" them, because every one of those
/// differences produces a tower that runs and answers wrongly.
@Suite("Gemma 4 vision geometry")
struct Gemma4VisionConfigTests {

    private let config = Gemma4VisionConfig.a4b

    @Test("The transcribed constants match the published config")
    func constants() {
        #expect(config.depth == 27)
        #expect(config.hiddenSize == 1152)
        #expect(config.headDim == 72)
        #expect(config.intermediateSize == 4304)
        #expect(config.outHiddenSize == 2816, "the text model's hidden size")
        #expect(config.patchElements == 768, "16 x 16 x 3, one frame")
        #expect(config.softTokens == 280)
        #expect(config.patchesPerToken == 9, "a 3x3 average pool, not a 2x2 merge")
        #expect(config.maximumPatches == 2520)
        #expect(config.sideMultiple == 48, "so the pool divides both sides")
        #expect(config.positionEmbeddingSize == 10240)
        #expect(config.rotaryChannelsPerAxis == 36, "half a head to each axis")
    }

    /// The two values most likely to be copied from Qwen's tower, where they differ.
    @Test("The attention scale is one and the rotary base is a hundred")
    func theTwoThatLookLikeTypos() {
        #expect(config.attentionScale == 1.0, "not 1/sqrt(72); the reference sets it outright")
        #expect(config.ropeTheta == 100, "not 10000; these are patch coordinates, not tokens")
        #expect(config.attentionScale != 1 / Float(config.headDim).squareRoot())
    }

    @Test("Normalization spans minus one to one")
    func normalization() {
        #expect(config.normalize(0) == -1)
        #expect(config.normalize(255) == 1)
        #expect(abs(config.normalize(128) - 0.00392) < 1e-4)
    }

    // MARK: - Resizing, against the reference

    /// `(height, width, expected height, expected width, expected tokens)`.
    ///
    /// Generated by running `get_aspect_ratio_preserving_size` from the checkpoint's own image
    /// processor, not computed by hand. The rows that matter are the ones exercising a branch:
    /// 240x320 is scaled **up**, 1x150 rounds a side to zero and takes the thin-image path, and
    /// the square cases must land exactly on 768.
    static let cases: [(Int, Int, Int, Int, Int)] = [
        (3024, 4032, 672, 912, 266),
        (1440, 2560, 576, 1056, 264),
        (240, 320, 672, 912, 266),
        (1024, 1024, 768, 768, 256),
        (768, 768, 768, 768, 256),
        (100, 50, 1104, 528, 253),
        (50, 100, 528, 1104, 253),
        (4000, 3000, 912, 672, 266),
        (1, 150, 48, 9792, 204),
        (2000, 1500, 912, 672, 266),
    ]

    @Test("Resizing reproduces the reference", arguments: cases)
    func resize(testCase: (Int, Int, Int, Int, Int)) throws {
        let (height, width, expectedHeight, expectedWidth, expectedTokens) = testCase
        let sized = try config.resizedDimensions(height: height, width: width)
        #expect(
            sized.height == expectedHeight && sized.width == expectedWidth,
            "\(width)x\(height) became \(sized.width)x\(sized.height), reference says \(expectedWidth)x\(expectedHeight)")

        let grid = config.grid(forResizedHeight: sized.height, width: sized.width)
        #expect(config.tokenCount(forGridHeight: grid.height, width: grid.width) == expectedTokens)
    }

    /// A small image is enlarged, which is the opposite of what a "budget" suggests.
    @Test("A thumbnail is scaled up to fill the budget")
    func smallImagesAreEnlarged() throws {
        let sized = try config.resizedDimensions(height: 240, width: 320)
        #expect(sized.width > 320 && sized.height > 240, "a thumbnail was left small")
    }

    /// The token count is a property of the image, not a constant.
    @Test("Different shapes take different numbers of tokens")
    func tokenCountVaries() throws {
        var counts = Set<Int>()
        for (h, w) in [(1024, 1024), (1440, 2560), (100, 50), (1, 150)] {
            let sized = try config.resizedDimensions(height: h, width: w)
            let grid = config.grid(forResizedHeight: sized.height, width: sized.width)
            counts.insert(config.tokenCount(forGridHeight: grid.height, width: grid.width))
        }
        #expect(counts.count > 1, "every shape took the same number of tokens")
        #expect(counts.allSatisfy { $0 <= config.softTokens }, "an image exceeded the budget")
    }

    /// Every accepted image gives a grid the pooler can consume, and stays inside the budget.
    @Test("Every accepted image pools evenly and fits the budget")
    func invariants() throws {
        for height in stride(from: 8, through: 4000, by: 191) {
            for width in stride(from: 8, through: 4000, by: 227) {
                let sized = try config.resizedDimensions(height: height, width: width)
                #expect(sized.height % config.sideMultiple == 0, "\(width)x\(height)")
                #expect(sized.width % config.sideMultiple == 0, "\(width)x\(height)")

                let grid = config.grid(forResizedHeight: sized.height, width: sized.width)
                #expect(grid.height % config.poolingKernelSize == 0)
                #expect(grid.width % config.poolingKernelSize == 0)
                let tokens = config.tokenCount(forGridHeight: grid.height, width: grid.width)
                #expect(tokens > 0 && tokens <= config.softTokens, "\(width)x\(height): \(tokens)")
                #expect(
                    grid.height * grid.width <= config.maximumPatches,
                    "\(width)x\(height) exceeded the patch budget")
            }
        }
    }

    @Test("A degenerate image is refused")
    func degenerate() {
        #expect(throws: Gemma4VisionConfig.ImageError.self) {
            _ = try config.resizedDimensions(height: 0, width: 100)
        }
    }

    // MARK: - Patch order

    /// Reading order, with `(x, y)` positions: column first, unlike Qwen's merge order.
    @Test("Patches are in reading order and positions are column-first")
    func patchOrder() {
        let width = 5
        #expect(config.patchPosition(atIndex: 0, gridWidth: width) == (x: 0, y: 0))
        #expect(config.patchPosition(atIndex: 4, gridWidth: width) == (x: 4, y: 0))
        #expect(config.patchPosition(atIndex: 5, gridWidth: width) == (x: 0, y: 1))
        #expect(config.patchPosition(atIndex: 7, gridWidth: width) == (x: 2, y: 1))

        // The whole grid is a permutation, and x never exceeds the width.
        var seen = Set<Int>()
        for index in 0..<(width * 4) {
            let p = config.patchPosition(atIndex: index, gridWidth: width)
            #expect(p.x < width && p.y < 4)
            seen.insert(p.y * width + p.x)
        }
        #expect(seen.count == width * 4)
    }
}
