import Foundation
import Testing

@testable import HydraCore

/// The image geometry, against the reference `smart_resize` rather than against reasoning.
///
/// This is the part of a vision pipeline where a mistake is invisible. Every wrong answer here
/// still produces a valid grid, a valid patch count and a plausible number of tokens; the tower
/// runs, the merger runs, and the model receives an image that is subtly the wrong shape. There
/// is no exception and no NaN to notice, so the only defence is a table of values produced by
/// the reference implementation and checked against ours.
///
/// The expectations below were generated by running HuggingFace's `smart_resize` with Qwen 3.6's
/// own parameters, factor 32 and the area bounds from `preprocessor_config.json`. They are not
/// hand-computed, which matters: hand-computing them would reproduce whatever misunderstanding
/// the implementation already has.
@Suite("Qwen 3.6 image geometry")
struct Qwen35VisionConfigTests {

    /// The reference's own budget, for the conformance table below.
    ///
    /// Hydra ships a tighter one, and that is a product decision rather than a disagreement with
    /// the checkpoint, so the two are tested separately: this suite checks that the resize
    /// reproduces `smart_resize` at the budget `preprocessor_config.json` publishes, and
    /// `shippedBudget` checks what a user actually gets. Folding them together would mean the
    /// conformance table silently re-encoded the product decision, and could no longer be
    /// regenerated from the reference.
    private var config: Qwen35VisionConfig {
        var config = Qwen35VisionConfig.a3b
        config.maximumTokens = 16384       // exactly the published 16,777,216 pixels
        return config
    }

    /// The transcribed constants, so a typo in one of them fails here rather than in a tower
    /// that produces slightly wrong embeddings.
    @Test("The geometry matches the published config")
    func constants() {
        #expect(config.depth == 27)
        #expect(config.hiddenSize == 1152)
        #expect(config.headDim == 72, "16 heads over 1152")
        #expect(config.intermediateSize == 4304)
        #expect(config.outHiddenSize == 2048, "the text model's hidden size")
        #expect(config.sizeFactor == 32, "patch 16 times a 2x2 merge")
        #expect(config.patchElements == 1536, "2 frames x 16 x 16 x 3 channels")
        #expect(config.mergedWidth == 4608, "four patches of 1152")
        #expect(config.positionGridSide == 48, "2304 learned positions is a 48x48 grid")
    }

    /// `(height, width, expected height, expected width, expected tokens)`.
    ///
    /// The interesting rows are the ones that exercise a branch: 224 and 64 are below the
    /// minimum area and get scaled **up**; 3000x4000 and 5000x5000 are above the maximum and get
    /// scaled down; 1024x768 is already legal and must not move; 37x1200 and 1x150 are extreme
    /// aspect ratios that survive because they are under 200:1.
    static let cases: [(Int, Int, Int, Int, Int)] = [
        (224, 224, 256, 256, 64),
        (1024, 768, 1024, 768, 768),
        (3000, 4000, 3008, 4000, 11750),
        (64, 64, 256, 256, 64),
        (100, 50, 384, 192, 72),
        (1080, 1920, 1088, 1920, 2040),
        (5000, 5000, 4096, 4096, 16384),
        (37, 1200, 64, 1472, 92),
        (512, 512, 512, 512, 256),
        (256, 256, 256, 256, 64),
        (33, 33, 256, 256, 64),
        (4096, 4096, 4096, 4096, 16384),
        (800, 600, 800, 608, 475),
        (1, 150, 32, 3136, 98),
        // The shrink branch, properly exercised. The table above reached it exactly once, at
        // 5000x5000, where the arithmetic is degenerate: the answer comes out 4096 whether the
        // scale is taken from the original area or the rounded one, and whether the sides are
        // floored or rounded. Two deliberately broken versions passed the whole table. These
        // rows separate them, 3000x5620 by 32 pixels on one side.
        (3000, 5620, 2976, 5600, 16275),
        (5000, 4000, 4576, 3648, 16302),
        (8000, 3000, 6688, 2496, 16302),
        (4200, 4100, 4128, 4032, 16254),
        (6000, 6000, 4096, 4096, 16384),
    ]

    @Test("Resizing reproduces the reference", arguments: cases)
    func resize(testCase: (Int, Int, Int, Int, Int)) throws {
        let (height, width, expectedHeight, expectedWidth, expectedTokens) = testCase
        let sized = try config.resizedDimensions(height: height, width: width)
        #expect(
            sized.height == expectedHeight && sized.width == expectedWidth,
            "\(width)x\(height) became \(sized.width)x\(sized.height), reference says \(expectedWidth)x\(expectedHeight)")

        let grid = config.grid(forResizedHeight: sized.height, width: sized.width)
        #expect(config.tokenCount(for: grid) == expectedTokens)
    }

    /// Whatever the input, the result is patchable and mergeable. This is the invariant the rest
    /// of the pipeline assumes without checking, so it is checked once, here, over a wide sweep.
    @Test("Every accepted image yields a grid the merger can consume")
    func invariants() throws {
        // Past the pixel ceiling as well as under it. A sweep that stopped at 3000x3000 never
        // exceeds 16.7 million pixels, so the ceiling assertion below could not fail and the
        // shrink branch was never entered at all.
        for height in stride(from: 1, through: 6000, by: 149) {
            for width in stride(from: 1, through: 6000, by: 211) {
                guard max(height, width) / min(height, width) <= 200 else { continue }
                let sized = try config.resizedDimensions(height: height, width: width)

                #expect(sized.height % config.sizeFactor == 0, "\(width)x\(height)")
                #expect(sized.width % config.sizeFactor == 0, "\(width)x\(height)")
                #expect(sized.height >= config.sizeFactor && sized.width >= config.sizeFactor)

                let grid = config.grid(forResizedHeight: sized.height, width: sized.width)
                #expect(grid.height % config.spatialMergeSize == 0, "\(width)x\(height)")
                #expect(grid.width % config.spatialMergeSize == 0, "\(width)x\(height)")
                #expect(config.tokenCount(for: grid) > 0)
                // The budget is the whole reason the branches exist; it must actually hold.
                #expect(
                    sized.height * sized.width <= config.maximumPixels,
                    "\(width)x\(height) resized past the pixel ceiling")
            }
        }
    }

    /// The reference refuses beyond 200:1, and so must this, rather than returning a degenerate
    /// grid that would be processed happily.
    @Test("An impossible aspect ratio is refused, not clamped")
    func extremeRatiosAreRefused() {
        #expect(throws: Qwen35VisionConfig.ImageError.self) {
            _ = try config.resizedDimensions(height: 1, width: 500)
        }
        #expect(throws: Qwen35VisionConfig.ImageError.self) {
            _ = try config.resizedDimensions(height: 0, width: 100)
        }
    }

    /// What Hydra actually ships, which is not the published ceiling.
    ///
    /// The published budget turns a 4032x3024 phone photograph into 11,844 tokens: roughly eight
    /// minutes of prefill on this machine before a word is produced, and a third of a 32k
    /// context spent on one image. That number is written for server deployments.
    ///
    /// **Nothing is refused at any budget.** A smaller number is a smaller image, because the
    /// resize scales every image into the budget; the cost is detail, not access.
    @Test("The shipped budget bounds an image at 1024 tokens")
    func shippedBudget() throws {
        let shipped = Qwen35VisionConfig.a3b
        #expect(shipped.maximumTokens == 1024)
        #expect(shipped.maximumPixels == 1_048_576, "1024 tokens of 1024 pixels each")

        // The photograph that motivated the cap, and a screenshot that is unaffected by it.
        for (height, width, ceiling) in [(3024, 4032, 1024), (1440, 2560, 1024), (240, 320, 1024)] {
            let sized = try shipped.resizedDimensions(height: height, width: width)
            let grid = shipped.grid(forResizedHeight: sized.height, width: sized.width)
            #expect(
                shipped.tokenCount(for: grid) <= ceiling,
                "\(width)x\(height) became \(shipped.tokenCount(for: grid)) tokens")
        }

        // A phone photograph is still a detailed image at this budget, not a thumbnail.
        let photo = try shipped.resizedDimensions(height: 3024, width: 4032)
        #expect(photo.width >= 1024, "the cap shrank a photograph to \(photo.width) wide")

        // And no setting can push past what the checkpoint was trained to position.
        var greedy = Qwen35VisionConfig.a3b
        greedy.maximumTokens = 1_000_000
        #expect(greedy.maximumPixels == Qwen35VisionConfig.publishedMaximumPixels)
    }

    /// A video's frames multiply the patches but not the grid, and the token count follows.
    @Test("Frames multiply the token count")
    func framesScale() {
        let one = Qwen35VisionConfig.Grid(temporal: 1, height: 16, width: 16)
        let four = Qwen35VisionConfig.Grid(temporal: 4, height: 16, width: 16)
        #expect(config.tokenCount(for: one) == 64)
        #expect(config.tokenCount(for: four) == 256)
    }
}

/// The patch ordering, which decides which pixels the merger folds together.
///
/// Reading order is the obvious implementation and it is wrong. The reference groups patches
/// into the 2x2 blocks the merger consumes, so four consecutive patches form a square. Nothing
/// downstream can detect the difference: the patch count is identical, the token count is
/// identical, every kernel runs, and the model receives an image whose content has been
/// scrambled within each block.
@Suite("Qwen 3.6 patch order")
struct Qwen35PatchOrderTests {

    private let config = Qwen35VisionConfig.a3b

    /// The reference permutation, written the way the reference writes it: a reshape to
    /// `(h/m, m, w/m, m)` and a transpose of the middle two axes, unrolled as nested loops.
    /// Deliberately *not* the closed form under test, so the two can disagree.
    private func reference(_ grid: Qwen35VisionConfig.Grid) -> [(Int, Int, Int)] {
        let m = config.spatialMergeSize
        var out: [(Int, Int, Int)] = []
        for frame in 0..<grid.temporal {
            for blockRow in 0..<(grid.height / m) {
                for blockColumn in 0..<(grid.width / m) {
                    for dy in 0..<m {
                        for dx in 0..<m {
                            out.append((frame, blockRow * m + dy, blockColumn * m + dx))
                        }
                    }
                }
            }
        }
        return out
    }

    @Test("The closed form reproduces the reference permutation")
    func matchesReference() {
        for (height, width) in [(2, 2), (4, 4), (4, 6), (6, 4), (8, 10), (16, 24), (64, 48)] {
            let grid = Qwen35VisionConfig.Grid(temporal: 1, height: height, width: width)
            let expected = reference(grid)
            for index in 0..<grid.patchCount {
                let got = config.patchPosition(atSequenceIndex: index, grid: grid)
                #expect(
                    got.frame == expected[index].0 && got.y == expected[index].1
                        && got.x == expected[index].2,
                    "\(width)x\(height) patch \(index): got \(got), reference \(expected[index])")
            }
        }
    }

    /// The property that makes it a *merge* order rather than reading order.
    @Test("Four consecutive patches form one 2x2 square")
    func consecutivePatchesFormASquare() {
        let grid = Qwen35VisionConfig.Grid(temporal: 1, height: 8, width: 12)
        for block in 0..<(grid.patchCount / 4) {
            let corners = (0..<4).map { config.patchPosition(atSequenceIndex: block * 4 + $0, grid: grid) }
            let ys = Set(corners.map(\.y)), xs = Set(corners.map(\.x))
            #expect(ys.count == 2 && xs.count == 2, "block \(block) is not a square: \(corners)")
            #expect(ys.max()! - ys.min()! == 1 && xs.max()! - xs.min()! == 1)
        }
    }

    /// Reading order would satisfy neither the reference nor the square property, and this
    /// states it so the distinction cannot be quietly lost.
    @Test("Reading order is a different permutation")
    func readingOrderDiffers() {
        let grid = Qwen35VisionConfig.Grid(temporal: 1, height: 4, width: 6)
        let mine = (0..<grid.patchCount).map { config.patchPosition(atSequenceIndex: $0, grid: grid) }
        let reading = (0..<grid.patchCount).map { (0, $0 / grid.width, $0 % grid.width) }
        #expect(
            zip(mine, reading).contains { $0.y != $1.1 || $0.x != $1.2 },
            "the implementation is in reading order, which is the failure this suite exists for")
    }

    /// Every patch is visited exactly once: a permutation, not a mapping that drops or repeats.
    @Test("The order is a permutation of the grid")
    func isAPermutation() {
        for (height, width) in [(4, 6), (16, 24), (188, 250)] {
            let grid = Qwen35VisionConfig.Grid(temporal: 2, height: height, width: width)
            var seen = Set<Int>()
            for index in 0..<grid.patchCount {
                let p = config.patchPosition(atSequenceIndex: index, grid: grid)
                #expect(p.y < height && p.x < width, "patch \(index) fell outside the grid")
                seen.insert((p.frame * height + p.y) * width + p.x)
            }
            #expect(seen.count == grid.patchCount, "\(width)x\(height) is not a permutation")
        }
    }
}
